### ISSUE TITLE
TODO list is inside the readme

### ISSUE THREAD

**Issue by ghost** [cpp-frug/materials#5]
The TODO list in the readme is redundant with the bugtracker. Therefore, there is a high risk that it will not be updated as long as TODOs are solved. Like all TODO files I've seen in projects I've compiled (and which had, obviously, that kind of notes).

---

La liste des choses à faire est redondance avec le gestionnaire de tickets (beurk le terme français sur ce coup). Du coup, il est très probable que ce fichier finira par être obsolète, ce qui est d'ailleurs ce que j'ai toujours vu dans les programmes que j'ai compilé (et qui, bien sûr, avaient ce type de notes)....

**Comment by olibre** [comment]
Oui, très bonne idée de déplacer les TODOs vers la pages des Issues.
Merci :-)
Je garde cette issues Open tant que les TODOs ne soient pas copiés...
